use_frameworks!

target 'ALWRefreshControl_Example' do
  pod 'ALWRefreshControl', :path => '../'

  target 'ALWRefreshControl_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
